version: "3"

services:
  postgres:
    image: postgres:latest
    env_file:
      - database.env # configure postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: adminer
    ports:
      - 8080:8080
